/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#9fe2ff",
        "surface-container": "#edeeec",
        "surface-bright": "#f9f9f8",
        "on-background": "#1a1c1b",
        "secondary": "#186d2d",
        "surface-variant": "#e2e3e1",
        "secondary-fixed-dim": "#87d98c",
        "primary": "#004e63",
        "on-primary-fixed": "#001f29",
        "on-secondary-fixed-variant": "#00531c",
        "on-error": "#ffffff",
        "surface-dim": "#d9dad9",
        "surface-container-highest": "#e2e3e1",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2f3130",
        "on-surface-variant": "#3f484c",
        "on-primary-fixed-variant": "#004d62",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffcfae",
        "on-secondary": "#ffffff",
        "surface": "#f9f9f8",
        "on-secondary-fixed": "#002107",
        "outline": "#6f787d",
        "tertiary-container": "#934b00",
        "primary-fixed-dim": "#86d0ef",
        "tertiary-fixed": "#ffdcc5",
        "on-secondary-container": "#1e7131",
        "surface-tint": "#006782",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#703800",
        "tertiary": "#703800",
        "background": "#f9f9f8",
        "secondary-container": "#9ff3a3",
        "inverse-on-surface": "#f0f1ef",
        "inverse-primary": "#86d0ef",
        "surface-container-low": "#f3f4f2",
        "primary-fixed": "#baeaff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#a2f6a6",
        "tertiary-fixed-dim": "#ffb781",
        "error": "#ba1a1a",
        "primary-container": "#006782",
        "on-surface": "#1a1c1b",
        "surface-container-high": "#e8e8e7",
        "outline-variant": "#bfc8cd",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
